package:
  name: murmurhash
  version: "0.24"

source:
  fn: murmurhash-0.24.tar.gz
  url: https://pypi.python.org/packages/source/m/murmurhash/murmurhash-0.24.tar.gz
  md5: 182d31e0c4aa34fdf0d57a78f7249108
  patches:
    - MurmurHash2.h.patch
    - MurmurHash3.h.patch           

build:
  script: $PYTHON setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  requires:
    - pytest
  commands:
    - py.test \tests

about:
  home: https://github.com/syllog1sm/cython-murmurhash
  summary: 'Cython bindings for murmurhash'
